### PR TITLE
add support for debian

### PR DESCRIPTION
**Pull request by semik**
Adding file `vars/debian.yml` to define *systemd-timesyncd* package name.

Without this change, is the role using just *systemd* as is described in `vars/default.yml` and the role is not able to install right package on Debian system.

### CODE REVIEW

**Comment by wookietreiber** [comment]
Thanks! Please also add these two to `molecule/default/molecule.yml` (I think [this](https://hub.docker.com/r/geerlingguy/docker-debian12-ansible) and [this](https://hub.docker.com/r/geerlingguy/docker-debian11-ansible) are the images that we need) and the corresponding names to the list in `.github/workflows/ansible.yml` so these are tested.

**Comment by semik** [comment]
Added as requested. Execution in my personal fork was successful: https://github.com/semik/ansible-role-systemd-timesyncd/actions/runs/11361749069

**Comment by semik** [comment]
@wookietreiber Is the PR ok now?

**Review by wookietreiber — APPROVED** [review]

**Comment by wookietreiber** [comment]
thanks again, released as v2.1.0

**Pull request merged**
